### ISSUE TITLE
关于pubmed数据集

### ISSUE THREAD

**Issue by DreamerDW** [cszhangzhen/ANRL#11]
您好！ANRL非常简洁高效！请问对于pubmed数据集，超参应该如何设置，对于这个数据集，我得到的结果一直很低，请问针对这个数据集，除了自动编码器的隐含层，还应该如何设置其他超参来得到理想的效果！谢谢！期待您的回复！

**Comment by cszhangzhen** [comment]
Hi，你好，可以参考一下这个回复 #9

**Comment by DreamerDW** [comment]
好的谢谢您！
