### ISSUE TITLE
该模型可以用于异构图吗？

### ISSUE THREAD

**Issue by Heath0** [cszhangzhen/ANRL#17]
如果用在异构图上，图中会有多种节点，每种节点的特征维度可能不一样。想问作者有没有解决方法？

**Comment by cszhangzhen** [comment]
该模型是为同构图设计的，如果你想对异构图进行建模的话，可以参考这篇文章的方法 Representation Learning for Attributed Multiplex Heterogeneous Network

**Comment by Heath0** [comment]
明白了，多谢您！！
