### ISSUE TITLE
数据集格式转化代码问题

### ISSUE THREAD

**Issue by hongyonghan** [cszhangzhen/ANRL#22]
作者您好！您能不能将下面这个格式的数据转化成citeseer.edgelist  citeseer.feature的代码开源出来啊？
ind.cora.allx
ind.cora.ally
ind.cora.graph
ind,coratest.index
ind,coratx
ind,cora.ty
ind,cora,x
ind.cora.y

**Comment by cszhangzhen** [comment]
你好，我当时使用的是原始的数据集不是从ind.citeseer那边转换过来的；原始数据集可以从这里下载https://relational.fit.cvut.cz/dataset/CiteSeer 原始网站貌似访问不了了https://relational.fit.cvut.cz/dataset/CiteSeer
