### ISSUE TITLE
Want more dataset

### ISSUE THREAD

**Issue by xdql** [cszhangzhen/ANRL#3]
I hope that you can share the other data sets of the test. The data set on the network cannot meet the experimental conditions. Your help will be very useful to me. Thank you.

**Comment by cszhangzhen** [comment]
Hi,

Facebook dataset is available at https://snap.stanford.edu/data/ego-Facebook.html
Citeseer and Pubmed datasets are available at https://linqs.soe.ucsc.edu/data

Unfortunately, UniID and Fraud Detection are two private datasets provided by Alibaba Group, so we are not permitted to give out these datasets.

**Comment by xdql** [comment]
Thank you very much, is it a similar project in the citeseer form of the Pubmed dataset, feature&label&edgelist or adjlist.

**Comment by cszhangzhen** [comment]
PubMed Diabetes in https://linqs.soe.ucsc.edu/data is what we used in the paper. It can be downloaded through the URL.
