### ISSUE TITLE
关于代码和论文

### ISSUE THREAD

**Issue by prejefferson** [cszhangzhen/ANRL#7]
您好，我是一位网络表示学习初学者，请问您提出的这个模型是无监督的还是有监督的？因为我看到链路预测的无监督任务以及节点分类的有监督任务，并且您的代码里面用到了标签信息。请问这个模型是有监督无监督都能做吗，无监督版本该如何实现呢

**Comment by cszhangzhen** [comment]
你好，

该模型是无监督的，学习节点表征的时候并没有用到节点的标签信息。

对于节点分类这样的有监督任务，先用该模型学习得到节点的表征，然后再利用标签信息和节点的表征训练有监督的分类器（例如SVM等）。对于链路预测也是同样的道理。一般来说，链路预测既可以采用有监督的方式（例如训练分类器判断两个节点之间是否有边）也可以采用无监督的方式（例如利用某种度量准则去判断两个节点之间是否有边）。

**Comment by prejefferson** [comment]
谢谢您！
