### ISSUE TITLE
How to apply ANRL to Pubmed dataset?

### ISSUE THREAD

**Issue by Cbl521** [cszhangzhen/ANRL#9]
Excuse me, I wonder how to apply ANRL to Pubmed dataset?
I changed the read_feature function to read Pubmed feature matrix like:
    features = sio.loadmat(inputFileName)
    features = features['feature']
I adjusted the parameter in tf.app,flags and changed the struct parameter in config.py to [None, 200 ,None]. 
However the result is confusing, please tell me what other operations should I do? Thanks a lot.

**Comment by cszhangzhen** [comment]
Hi,

To be consistent with citeseer dataset,  I transform the features into 1 and 0 . Try to add the following line:
features[features>0] = 1.0

Or you can normalize the features.

**Comment by Cbl521** [comment]
> Hi,
> 
> To be consistent with citeseer dataset, I transform the features into 1 and 0 . Try to add the following line:
> features[features>0] = 1.0
> 
> Or you can normalize the features.

Thanks for your advice, it works!
Best wishes!

**Comment by cszhangzhen** [comment]
Feel free to let me know if you have any question 😊
